/* tslint:disable */
/* eslint-disable */
/**
 * Meal Planner API
 * Meal Planner is an API service for planning meals and managing recipes.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AllergenResponse,
} from '../models/index';
import {
    AllergenResponseFromJSON,
    AllergenResponseToJSON,
} from '../models/index';

/**
 * 
 */
export class AllergensApi extends runtime.BaseAPI {

    /**
     * Retrieves a list of all allergens
     * Get all allergens
     */
    async getAllAllergensRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AllergenResponse>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};


        let urlPath = `/allergens`;

        const response = await this.request({
            path: urlPath,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AllergenResponseFromJSON));
    }

    /**
     * Retrieves a list of all allergens
     * Get all allergens
     */
    async getAllAllergens(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AllergenResponse>> {
        const response = await this.getAllAllergensRaw(initOverrides);
        return await response.value();
    }

}
