/* tslint:disable */
/* eslint-disable */
/**
 * Meal Planner API
 * Meal Planner is an API service for planning meals and managing recipes.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface AllergenResponse
 */
export interface AllergenResponse {
    /**
     * 
     * @type {string}
     * @memberof AllergenResponse
     */
    description?: string;
    /**
     * 
     * @type {string}
     * @memberof AllergenResponse
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof AllergenResponse
     */
    name?: string;
}

/**
 * Check if a given object implements the AllergenResponse interface.
 */
export function instanceOfAllergenResponse(value: object): value is AllergenResponse {
    return true;
}

export function AllergenResponseFromJSON(json: any): AllergenResponse {
    return AllergenResponseFromJSONTyped(json, false);
}

export function AllergenResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllergenResponse {
    if (json == null) {
        return json;
    }
    return {
        
        'description': json['description'] == null ? undefined : json['description'],
        'id': json['id'] == null ? undefined : json['id'],
        'name': json['name'] == null ? undefined : json['name'],
    };
}

export function AllergenResponseToJSON(json: any): AllergenResponse {
    return AllergenResponseToJSONTyped(json, false);
}

export function AllergenResponseToJSONTyped(value?: AllergenResponse | null, ignoreDiscriminator: boolean = false): any {
    if (value == null) {
        return value;
    }

    return {
        
        'description': value['description'],
        'id': value['id'],
        'name': value['name'],
    };
}

